package com.nway.spring.jdbc.performance.dal.mapper;

import com.nway.spring.jdbc.performance.dal.po.ComputerPoEntity;
import com.nway.spring.jdbc.performance.dal.po.ComputerPoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("ComputerMapperGe")
public interface ComputerMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<ComputerPoEntity> selectByExampleWithBLOBs(ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<ComputerPoEntity> selectByExample(ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    ComputerPoEntity selectByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") ComputerPoEntity record, @Param("example") ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleWithBLOBs(@Param("record") ComputerPoEntity record, @Param("example") ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") ComputerPoEntity record, @Param("example") ComputerPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeyWithBLOBs(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsert(@Param("list") List<ComputerPoEntity> list);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsertSelective(@Param("list") List<ComputerPoEntity> list, @Param("selective") ComputerPoEntity.Column ... selective);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsert(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertSelective(ComputerPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertWithBLOBs(ComputerPoEntity record);
}