package com.nway.spring.jdbc.performance.dal.mapper;

import com.nway.spring.jdbc.performance.dal.po.ComputerSoftwarePoEntity;
import com.nway.spring.jdbc.performance.dal.po.ComputerSoftwarePoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("ComputerSoftwareMapperGe")
public interface ComputerSoftwareMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(ComputerSoftwarePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(ComputerSoftwarePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(ComputerSoftwarePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(ComputerSoftwarePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<ComputerSoftwarePoEntity> selectByExample(ComputerSoftwarePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") ComputerSoftwarePoEntity record, @Param("example") ComputerSoftwarePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") ComputerSoftwarePoEntity record, @Param("example") ComputerSoftwarePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsert(@Param("list") List<ComputerSoftwarePoEntity> list);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsertSelective(@Param("list") List<ComputerSoftwarePoEntity> list, @Param("selective") ComputerSoftwarePoEntity.Column ... selective);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsert(ComputerSoftwarePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertSelective(ComputerSoftwarePoEntity record);
}