package com.nway.spring.jdbc.performance.dal.mapper;

import com.nway.spring.jdbc.performance.dal.po.MainframePoEntity;
import com.nway.spring.jdbc.performance.dal.po.MainframePoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("MainframeMapperGe")
public interface MainframeMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MainframePoEntity> selectByExampleWithBLOBs(MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MainframePoEntity> selectByExample(MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    MainframePoEntity selectByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") MainframePoEntity record, @Param("example") MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleWithBLOBs(@Param("record") MainframePoEntity record, @Param("example") MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") MainframePoEntity record, @Param("example") MainframePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeyWithBLOBs(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsert(@Param("list") List<MainframePoEntity> list);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsertSelective(@Param("list") List<MainframePoEntity> list, @Param("selective") MainframePoEntity.Column ... selective);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsert(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertSelective(MainframePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mainframe
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertWithBLOBs(MainframePoEntity record);
}