package com.nway.spring.jdbc.performance.dal.mapper;

import com.nway.spring.jdbc.performance.dal.po.MonitorPoEntity;
import com.nway.spring.jdbc.performance.dal.po.MonitorPoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("MonitorMapperGe")
public interface MonitorMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MonitorPoEntity> selectByExampleWithBLOBs(MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MonitorPoEntity> selectByExample(MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    MonitorPoEntity selectByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") MonitorPoEntity record, @Param("example") MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleWithBLOBs(@Param("record") MonitorPoEntity record, @Param("example") MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") MonitorPoEntity record, @Param("example") MonitorPoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeyWithBLOBs(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsert(@Param("list") List<MonitorPoEntity> list);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsertSelective(@Param("list") List<MonitorPoEntity> list, @Param("selective") MonitorPoEntity.Column ... selective);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsert(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertSelective(MonitorPoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_monitor
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertWithBLOBs(MonitorPoEntity record);
}