package com.nway.spring.jdbc.performance.dal.mapper;

import com.nway.spring.jdbc.performance.dal.po.MousePoEntity;
import com.nway.spring.jdbc.performance.dal.po.MousePoQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository("MouseMapperGe")
public interface MouseMapper {
    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    long countByExample(MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByExample(MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int deleteByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insert(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int insertSelective(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MousePoEntity> selectByExampleWithBLOBs(MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    List<MousePoEntity> selectByExample(MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    MousePoEntity selectByPrimaryKey(Integer id);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleSelective(@Param("record") MousePoEntity record, @Param("example") MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExampleWithBLOBs(@Param("record") MousePoEntity record, @Param("example") MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByExample(@Param("record") MousePoEntity record, @Param("example") MousePoQuery example);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeySelective(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKeyWithBLOBs(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int updateByPrimaryKey(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsert(@Param("list") List<MousePoEntity> list);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int batchInsertSelective(@Param("list") List<MousePoEntity> list, @Param("selective") MousePoEntity.Column ... selective);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsert(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertSelective(MousePoEntity record);

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_mouse
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    int upsertWithBLOBs(MousePoEntity record);
}