package com.nway.spring.jdbc.performance.dal.po;

import com.nway.spring.jdbc.performance.entity.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_computer
 *
 * @mbg.generated do_not_delete_during_merge
 * @project https://github.com/itfsw/mybatis-generator-plugin
 */
public class ComputerPoEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.model
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.price
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.production_date
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Date productionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.keyboard_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer keyboardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.mainframe_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer mainframeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.monitor_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer monitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.mouse_id
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Integer mouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_computer.photo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private byte[] photo;

    private MainframePoEntity mainframe;

    private MonitorPoEntity monitor;

    private MousePoEntity mouse;

    private KeyboardPoEntity keyboard;

    private List<SoftwarePoEntity> software;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_computer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.id
     *
     * @return the value of t_computer.id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.id
     *
     * @param id the value for t_computer.id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.brand
     *
     * @return the value of t_computer.brand
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.brand
     *
     * @param brand the value for t_computer.brand
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.model
     *
     * @return the value of t_computer.model
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.model
     *
     * @param model the value for t_computer.model
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.price
     *
     * @return the value of t_computer.price
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.price
     *
     * @param price the value for t_computer.price
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.production_date
     *
     * @return the value of t_computer.production_date
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.production_date
     *
     * @param productionDate the value for t_computer.production_date
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.keyboard_id
     *
     * @return the value of t_computer.keyboard_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getKeyboardId() {
        return keyboardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.keyboard_id
     *
     * @param keyboardId the value for t_computer.keyboard_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setKeyboardId(Integer keyboardId) {
        this.keyboardId = keyboardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.mainframe_id
     *
     * @return the value of t_computer.mainframe_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getMainframeId() {
        return mainframeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.mainframe_id
     *
     * @param mainframeId the value for t_computer.mainframe_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setMainframeId(Integer mainframeId) {
        this.mainframeId = mainframeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.monitor_id
     *
     * @return the value of t_computer.monitor_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getMonitorId() {
        return monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.monitor_id
     *
     * @param monitorId the value for t_computer.monitor_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setMonitorId(Integer monitorId) {
        this.monitorId = monitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.mouse_id
     *
     * @return the value of t_computer.mouse_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getMouseId() {
        return mouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.mouse_id
     *
     * @param mouseId the value for t_computer.mouse_id
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setMouseId(Integer mouseId) {
        this.mouseId = mouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_computer.photo
     *
     * @return the value of t_computer.photo
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_computer.photo
     *
     * @param photo the value for t_computer.photo
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_computer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        brand("brand", "brand", "VARCHAR", false),
        model("model", "model", "VARCHAR", false),
        price("price", "price", "REAL", false),
        productionDate("production_date", "productionDate", "DATE", false),
        keyboardId("keyboard_id", "keyboardId", "INTEGER", false),
        mainframeId("mainframe_id", "mainframeId", "INTEGER", false),
        monitorId("monitor_id", "monitorId", "INTEGER", false),
        mouseId("mouse_id", "mouseId", "INTEGER", false),
        photo("photo", "photo", "LONGVARBINARY", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_computer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    public MainframePoEntity getMainframe() {
        return mainframe;
    }

    public void setMainframe(MainframePoEntity mainframe) {
        this.mainframe = mainframe;
    }

    public MonitorPoEntity getMonitor() {
        return monitor;
    }

    public void setMonitor(MonitorPoEntity monitor) {
        this.monitor = monitor;
    }

    public MousePoEntity getMouse() {
        return mouse;
    }

    public void setMouse(MousePoEntity mouse) {
        this.mouse = mouse;
    }

    public KeyboardPoEntity getKeyboard() {
        return keyboard;
    }

    public void setKeyboard(KeyboardPoEntity keyboard) {
        this.keyboard = keyboard;
    }

    public List<SoftwarePoEntity> getSoftware() {
        return software;
    }

    public void setSoftware(List<SoftwarePoEntity> software) {
        this.software = software;
    }
}