package com.nway.spring.jdbc.performance.dal.po;

import java.util.ArrayList;
import java.util.List;

public class ComputerSoftwarePoQuery {
    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_computer_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    protected String orderByClause;

    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_computer_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    protected boolean distinct;

    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_computer_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    protected List<Criteria> oredCriteria;

    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_computer_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    protected Integer offset;

    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_computer_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    protected Integer rows;

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public ComputerSoftwarePoQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public boolean isDistinct() {
        return distinct;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public Integer getOffset() {
        return this.offset;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public Integer getRows() {
        return this.rows;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public ComputerSoftwarePoQuery limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public ComputerSoftwarePoQuery limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
            * This method was generated by MyBatis Generator.
            * This method corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public ComputerSoftwarePoQuery page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComputerIdIsNull() {
            addCriterion("Computer_id is null");
            return (Criteria) this;
        }

        public Criteria andComputerIdIsNotNull() {
            addCriterion("Computer_id is not null");
            return (Criteria) this;
        }

        public Criteria andComputerIdEqualTo(Integer value) {
            addCriterion("Computer_id =", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdNotEqualTo(Integer value) {
            addCriterion("Computer_id <>", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdGreaterThan(Integer value) {
            addCriterion("Computer_id >", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Computer_id >=", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdLessThan(Integer value) {
            addCriterion("Computer_id <", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdLessThanOrEqualTo(Integer value) {
            addCriterion("Computer_id <=", value, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdIn(List<Integer> values) {
            addCriterion("Computer_id in", values, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdNotIn(List<Integer> values) {
            addCriterion("Computer_id not in", values, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdBetween(Integer value1, Integer value2) {
            addCriterion("Computer_id between", value1, value2, "computerId");
            return (Criteria) this;
        }

        public Criteria andComputerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Computer_id not between", value1, value2, "computerId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdIsNull() {
            addCriterion("software_id is null");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdIsNotNull() {
            addCriterion("software_id is not null");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdEqualTo(Integer value) {
            addCriterion("software_id =", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdNotEqualTo(Integer value) {
            addCriterion("software_id <>", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdGreaterThan(Integer value) {
            addCriterion("software_id >", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("software_id >=", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdLessThan(Integer value) {
            addCriterion("software_id <", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdLessThanOrEqualTo(Integer value) {
            addCriterion("software_id <=", value, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdIn(List<Integer> values) {
            addCriterion("software_id in", values, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdNotIn(List<Integer> values) {
            addCriterion("software_id not in", values, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdBetween(Integer value1, Integer value2) {
            addCriterion("software_id between", value1, value2, "softwareId");
            return (Criteria) this;
        }

        public Criteria andSoftwareIdNotBetween(Integer value1, Integer value2) {
            addCriterion("software_id not between", value1, value2, "softwareId");
            return (Criteria) this;
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_computer_software
            *
            * @mbg.generated do_not_delete_during_merge
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
            * This class was generated by MyBatis Generator.
            * This class corresponds to the database table t_computer_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}