package com.nway.spring.jdbc.performance.dal.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

/**
                *
        * This class was generated by MyBatis Generator.
        * This class corresponds to the database table t_software
        *
        * @mbg.generated do_not_delete_during_merge
        * @project https://github.com/itfsw/mybatis-generator-plugin
        */
public class SoftwarePoEntity implements Serializable {
    /**
                *
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database column t_software.id
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private Integer id;

    /**
                *
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database column t_software.name
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private String name;

    /**
                *
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database column t_software.file_size
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private Long fileSize;

    /**
                *
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database column t_software.vender
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private String vender;

    /**
                *
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database column t_software.version
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private String version;

    /**
                * This field was generated by MyBatis Generator.
                * This field corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    private static final long serialVersionUID = 1L;

    /**
                * This method was generated by MyBatis Generator.
                * This method returns the value of the database column t_software.id
                *
                * @return the value of t_software.id
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public Integer getId() {
        return id;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method sets the value of the database column t_software.id
                *
                * @param id the value for t_software.id
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method returns the value of the database column t_software.name
                *
                * @return the value of t_software.name
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public String getName() {
        return name;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method sets the value of the database column t_software.name
                *
                * @param name the value for t_software.name
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public void setName(String name) {
        this.name = name;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method returns the value of the database column t_software.file_size
                *
                * @return the value of t_software.file_size
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public Long getFileSize() {
        return fileSize;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method sets the value of the database column t_software.file_size
                *
                * @param fileSize the value for t_software.file_size
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method returns the value of the database column t_software.vender
                *
                * @return the value of t_software.vender
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public String getVender() {
        return vender;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method sets the value of the database column t_software.vender
                *
                * @param vender the value for t_software.vender
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public void setVender(String vender) {
        this.vender = vender;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method returns the value of the database column t_software.version
                *
                * @return the value of t_software.version
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public String getVersion() {
        return version;
    }

    /**
                * This method was generated by MyBatis Generator.
                * This method sets the value of the database column t_software.version
                *
                * @param version the value for t_software.version
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
            * This enum was generated by MyBatis Generator.
            * This enum corresponds to the database table t_software
            *
            * @mbg.generated
            * @project https://github.com/itfsw/mybatis-generator-plugin
            */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", false),
        fileSize("file_size", "fileSize", "BIGINT", false),
        vender("vender", "vender", "VARCHAR", false),
        version("version", "version", "VARCHAR", false);

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private static final String ENDING_DELIMITER = "\"";

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private final String column;

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private final boolean isColumnNameDelimited;

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private final String javaProperty;

        /**
                    * This field was generated by MyBatis Generator.
                    * This field corresponds to the database table t_software
                    *
                    * @mbg.generated
                    * @project https://github.com/itfsw/mybatis-generator-plugin
                    */
        private final String jdbcType;

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String value() {
            return this.column;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getValue() {
            return this.column;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public static Column[] all() {
            return Column.values();
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
                * This method was generated by MyBatis Generator.
                * This method corresponds to the database table t_software
                *
                * @mbg.generated
                * @project https://github.com/itfsw/mybatis-generator-plugin
                */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}